In [1]:
import torch

In [2]:
torch.__version__

'1.5.1'

In [3]:
torch.cuda.is_available()

True

In [4]:
torch.cuda.get_device_name(0)

'GeForce MX250'

In [5]:
import numpy as np
lst=[3,4,5,6]
arr=np.array(lst)

In [6]:
arr

array([3, 4, 5, 6])

In [7]:
arr.dtype

dtype('int32')

# Convert Numpy To Pytorch Tensors¶

In [8]:
tensors=torch.from_numpy(arr)

In [9]:
tensors

tensor([3, 4, 5, 6], dtype=torch.int32)

In [11]:
tensors[0:2]

tensor([3, 4], dtype=torch.int32)

In [12]:
tensors[3]=89

In [13]:
tensors

tensor([ 3,  4,  5, 89], dtype=torch.int32)

In [15]:
arr #both tensors and array share same memeory

array([ 3,  4,  5, 89])

In [16]:
# to prevent above problem
tensor_arr=torch.tensor(arr)

In [18]:
tensor_arr[3]=55

In [19]:
arr

array([ 3,  4,  5, 89])

In [20]:
tensor_arr

tensor([ 3,  4,  5, 55], dtype=torch.int32)

In [26]:
torch.zeros(3,6)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [29]:
np.arange(0,28,2).reshape(7,2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [20, 22],
       [24, 26]])

In [30]:
torch.tensor(np.arange(0,28,2).reshape(7,2))

tensor([[ 0,  2],
        [ 4,  6],
        [ 8, 10],
        [12, 14],
        [16, 18],
        [20, 22],
        [24, 26]], dtype=torch.int32)

# Arithmetic Operations

In [31]:
a = torch.tensor([3,4,5], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(a + b)

tensor([ 7.,  9., 11.])


In [35]:
C=torch.zeros(4)
C

tensor([0., 0., 0., 0.])

In [37]:
torch.add(a,b,out=C)

tensor([ 7.,  9., 11.])

In [38]:
C

tensor([ 7.,  9., 11.])

In [39]:
torch.add(a,b)

tensor([ 7.,  9., 11.])

In [40]:
torch.add(a,b).sum()

tensor(27.)

# Dot Products and Mult Operations


In [41]:
x= torch.tensor([3,4,5], dtype=torch.float)
y = torch.tensor([4,5,6], dtype=torch.float)

In [42]:
x.mul(y)


tensor([12., 20., 30.])

In [43]:
x.mul(y).sum()


tensor(62.)

In [44]:
x.dot(y)

tensor(62.)

In [45]:
#Matrix Multiplicationa

In [46]:
x = torch.tensor([[1,4,2],[1,5,5]], dtype=torch.float)
y = torch.tensor([[5,7],[8,6],[9,11]], dtype=torch.float)

In [47]:
x.matmul(y)

tensor([[55., 53.],
        [90., 92.]])

In [48]:
x.mm(y)

tensor([[55., 53.],
        [90., 92.]])

In [49]:
x@y

tensor([[55., 53.],
        [90., 92.]])